"""Auto-generated MCP server for http://127.0.0.1:43987.

Generated by Agent-See v0.1.0
Capabilities: 14
Source: http://127.0.0.1:43987

Important: this runtime separates interface generation from operational
readiness. It includes bounded retries, approval gates, and session limits,
but still requires operator-controlled credentials, monitoring, and deployment
policy review.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import time
import uuid
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from enum import Enum
from typing import Any

import httpx
from mcp.server.fastmcp import FastMCP

logging.basicConfig(
    level=getattr(logging, os.environ.get("LOG_LEVEL", "INFO").upper(), logging.INFO),
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
logger = logging.getLogger(__name__)


class ExecutionBackend(str, Enum):
    API = "api"
    BROWSER = "browser"
    HYBRID = "hybrid"


@dataclass(frozen=True)
class RuntimeSettings:
    target_url: str
    port: int
    request_timeout_seconds: float
    browser_timeout_ms: int
    api_max_retries: int
    browser_max_retries: int
    retry_backoff_seconds: float
    allow_unsafe_automation: bool
    browser_headless: bool
    session_ttl_seconds: int
    max_sessions: int
    log_level: str

    @classmethod
    def from_env(cls) -> "RuntimeSettings":
        return cls(
            target_url=os.environ.get("TARGET_URL", "http://127.0.0.1:43987"),
            port=int(os.environ.get("PORT", "8000")),
            request_timeout_seconds=float(os.environ.get("REQUEST_TIMEOUT_SECONDS", "30")),
            browser_timeout_ms=int(os.environ.get("BROWSER_TIMEOUT_MS", "30000")),
            api_max_retries=int(os.environ.get("API_MAX_RETRIES", "2")),
            browser_max_retries=int(os.environ.get("BROWSER_MAX_RETRIES", "1")),
            retry_backoff_seconds=float(os.environ.get("RETRY_BACKOFF_SECONDS", "0.5")),
            allow_unsafe_automation=os.environ.get("AGENT_SEE_ALLOW_UNSAFE_AUTOMATION", "false").lower() == "true",
            browser_headless=os.environ.get("BROWSER_HEADLESS", "true").lower() != "false",
            session_ttl_seconds=int(os.environ.get("SESSION_TTL_SECONDS", "3600")),
            max_sessions=int(os.environ.get("MAX_SESSIONS", "200")),
            log_level=os.environ.get("LOG_LEVEL", "INFO").upper(),
        )


SETTINGS = RuntimeSettings.from_env()
logging.getLogger().setLevel(getattr(logging, SETTINGS.log_level, logging.INFO))

mcp = FastMCP(
    "http://127.0.0.1:43987",
    description="Agent-optimized interface for http://127.0.0.1:43987",
)

ROUTE_MAP = {
  "base_url": "http://127.0.0.1:43987",
  "routes": {
    "list_products": {
      "method": "GET",
      "path": "/products",
      "path_params": [],
      "query_params": [
        "category",
        "limit",
        "page",
        "query",
        "min_price",
        "max_price"
      ],
      "body_params": [],
      "content_type": "application/json"
    },
    "get_product_details": {
      "method": "GET",
      "path": "/products/{productId}",
      "path_params": [
        "productId"
      ],
      "query_params": [
        "product_id"
      ],
      "body_params": [],
      "content_type": "application/json"
    },
    "get_cart": {
      "method": "GET",
      "path": "/cart",
      "path_params": [],
      "query_params": [],
      "body_params": [],
      "content_type": "application/json"
    },
    "add_to_cart": {
      "method": "POST",
      "path": "/cart/items",
      "path_params": [],
      "query_params": [],
      "body_params": [
        "product_id",
        "quantity",
        "variant_id"
      ],
      "content_type": "application/json"
    },
    "submit_checkout": {
      "method": "POST",
      "path": "/checkout",
      "path_params": [],
      "query_params": [],
      "body_params": [
        "shipping_address",
        "email",
        "shipping_method",
        "full_name",
        "address",
        "zip_code"
      ],
      "content_type": "application/json"
    },
    "get_order_status": {
      "method": "GET",
      "path": "/orders/{orderId}",
      "path_params": [
        "orderId"
      ],
      "query_params": [
        "order_id"
      ],
      "body_params": [],
      "content_type": "application/json"
    }
  }
}
APPROVAL_POLICY = {
  "list_products": {
    "require_confirmation": false,
    "notes": [
      "Execution path is grounded in a discovered API route, but it has not been marked as live-verified by the generator.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context."
    ]
  },
  "get_product_details": {
    "require_confirmation": false,
    "notes": [
      "Execution path is grounded in a discovered API route, but it has not been marked as live-verified by the generator.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context."
    ]
  },
  "get_cart": {
    "require_confirmation": false,
    "notes": [
      "Execution path is grounded in a discovered API route, but it has not been marked as live-verified by the generator.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context."
    ]
  },
  "add_to_cart": {
    "require_confirmation": false,
    "notes": [
      "Execution path is grounded in a discovered API route, but it has not been marked as live-verified by the generator.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context."
    ]
  },
  "submit_checkout": {
    "require_confirmation": true,
    "notes": [
      "Execution path is grounded in a discovered API route, but it has not been marked as live-verified by the generator.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context.",
      "Human confirmation should be required before executing irreversible, payment-related, or identity-sensitive actions."
    ]
  },
  "get_order_status": {
    "require_confirmation": false,
    "notes": [
      "Execution path is grounded in a discovered API route, but it has not been marked as live-verified by the generator.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context."
    ]
  },
  "search_items": {
    "require_confirmation": true,
    "notes": [
      "Browser execution is generated from discovered DOM or network evidence and may require site-specific selector hardening.",
      "Human confirmation should be required before executing irreversible, payment-related, or identity-sensitive actions."
    ]
  },
  "send_message": {
    "require_confirmation": true,
    "notes": [
      "Browser execution is generated from discovered DOM or network evidence and may require site-specific selector hardening.",
      "Human confirmation should be required before executing irreversible, payment-related, or identity-sensitive actions."
    ]
  },
  "get_business_info": {
    "require_confirmation": false,
    "notes": [
      "Browser execution is generated from discovered DOM or network evidence and may require site-specific selector hardening."
    ]
  },
  "check_inventory": {
    "require_confirmation": false,
    "notes": [
      "This capability is currently represented structurally and may need a site-specific executor before production use."
    ]
  },
  "remove_from_cart": {
    "require_confirmation": false,
    "notes": [
      "This capability is currently represented structurally and may need a site-specific executor before production use.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context."
    ]
  },
  "apply_coupon": {
    "require_confirmation": false,
    "notes": [
      "This capability is currently represented structurally and may need a site-specific executor before production use."
    ]
  },
  "calculate_shipping": {
    "require_confirmation": false,
    "notes": [
      "This capability is currently represented structurally and may need a site-specific executor before production use."
    ]
  },
  "initiate_return": {
    "require_confirmation": false,
    "notes": [
      "This capability is currently represented structurally and may need a site-specific executor before production use."
    ]
  }
}
TOOL_METADATA = {
  "list_products": {
    "backend": "api",
    "readiness": "route_mapped",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "none",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      }
    ]
  },
  "get_product_details": {
    "backend": "api",
    "readiness": "route_mapped",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "none",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      }
    ]
  },
  "get_cart": {
    "backend": "api",
    "readiness": "route_mapped",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "none",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      }
    ]
  },
  "add_to_cart": {
    "backend": "api",
    "readiness": "route_mapped",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "none",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      }
    ]
  },
  "submit_checkout": {
    "backend": "api",
    "readiness": "route_mapped",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "confirmation_required",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      },
      {
        "code": "PAYMENT_REQUIRED",
        "description": "Human confirmation required before this action can proceed",
        "recovery": "human_intervention",
        "retryable": false
      }
    ]
  },
  "get_order_status": {
    "backend": "api",
    "readiness": "route_mapped",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "none",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      }
    ]
  },
  "search_items": {
    "backend": "browser",
    "readiness": "generated_browser",
    "verification": "inferred",
    "requires_session": false,
    "approval_requirement": "confirmation_required",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      },
      {
        "code": "PAYMENT_REQUIRED",
        "description": "Human confirmation required before this action can proceed",
        "recovery": "human_intervention",
        "retryable": false
      }
    ]
  },
  "send_message": {
    "backend": "browser",
    "readiness": "generated_browser",
    "verification": "inferred",
    "requires_session": false,
    "approval_requirement": "confirmation_required",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      },
      {
        "code": "PAYMENT_REQUIRED",
        "description": "Human confirmation required before this action can proceed",
        "recovery": "human_intervention",
        "retryable": false
      }
    ]
  },
  "get_business_info": {
    "backend": "browser",
    "readiness": "generated_browser",
    "verification": "inferred",
    "requires_session": false,
    "approval_requirement": "none",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      }
    ]
  },
  "check_inventory": {
    "backend": "hybrid",
    "readiness": "structural_only",
    "verification": "structural",
    "requires_session": false,
    "approval_requirement": "none",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      }
    ]
  },
  "remove_from_cart": {
    "backend": "hybrid",
    "readiness": "structural_only",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "none",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      }
    ]
  },
  "apply_coupon": {
    "backend": "hybrid",
    "readiness": "structural_only",
    "verification": "structural",
    "requires_session": false,
    "approval_requirement": "none",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      }
    ]
  },
  "calculate_shipping": {
    "backend": "hybrid",
    "readiness": "structural_only",
    "verification": "structural",
    "requires_session": false,
    "approval_requirement": "none",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      }
    ]
  },
  "initiate_return": {
    "backend": "hybrid",
    "readiness": "structural_only",
    "verification": "structural",
    "requires_session": false,
    "approval_requirement": "none",
    "errors": [
      {
        "code": "NOT_FOUND",
        "description": "Requested resource not found",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "INVALID_PARAM",
        "description": "Invalid parameter value",
        "recovery": "fix_params",
        "retryable": false
      },
      {
        "code": "SERVER_ERROR",
        "description": "Server error from original site",
        "recovery": "retry",
        "retryable": true
      }
    ]
  }
}
FORM_MAPPINGS = [
  {
    "tool_name": "search_items",
    "page_url": "http://127.0.0.1:43987/products",
    "form_selector": "form",
    "field_map": {
      "query": "[name='query']"
    },
    "submit_selector": "button[type=submit], input[type=submit]",
    "wait_for": "",
    "extract_selectors": {}
  },
  {
    "tool_name": "send_message",
    "page_url": "http://127.0.0.1:43987/contact",
    "form_selector": "form",
    "field_map": {
      "sender_name": "[name='sender_name']",
      "sender_email": "[name='sender_email']",
      "subject": "[name='subject']",
      "body": "[name='body']"
    },
    "submit_selector": "button[type=submit], input[type=submit]",
    "wait_for": "",
    "extract_selectors": {}
  },
  {
    "tool_name": "get_business_info",
    "page_url": "http://127.0.0.1:43987/about",
    "form_selector": "form",
    "field_map": {},
    "submit_selector": "button[type=submit], input[type=submit]",
    "wait_for": "",
    "extract_selectors": {}
  }
]
SCRAPING_RULES = [
  {
    "tool_name": "get_business_info",
    "page_url": "http://127.0.0.1:43987/about",
    "item_selector": "body",
    "field_selectors": {
      "text": "body"
    },
    "pagination_selector": ""
  }
]
RUNTIME_STATE = {
  "states": {
    "browsing": [
      "cart_review"
    ],
    "cart_review": [
      "checkout_ready",
      "browsing"
    ],
    "checkout_ready": [
      "payment_pending",
      "cart_review"
    ],
    "payment_pending": [
      "order_tracking"
    ],
    "order_tracking": []
  },
  "workflow_states": {
    "purchase_flow": [
      "browsing",
      "cart_review",
      "checkout_ready",
      "payment_pending",
      "order_tracking"
    ]
  },
  "session_entities": [
    "cart_session"
  ],
  "operational_notes": [
    "This state model is inferred from discovered capabilities and workflow order.",
    "It is intended to scaffold runtime continuity and should not be interpreted as a proof of live production behavior.",
    "E-commerce flows are modeled with an in-memory cart-style session unless the generated server is integrated with durable storage."
  ]
}

AUTH_HEADERS: dict[str, str] = {}
if os.environ.get("API_KEY"):
    AUTH_HEADERS["Authorization"] = f"Bearer {os.environ['API_KEY']}"
if os.environ.get("API_KEY_HEADER") and os.environ.get("API_KEY_VALUE"):
    AUTH_HEADERS[os.environ["API_KEY_HEADER"]] = os.environ["API_KEY_VALUE"]

STATUS_ERROR_MAP = {
    400: "INVALID_PARAM",
    401: "AUTH_FAILED",
    402: "PAYMENT_REQUIRED",
    403: "AUTH_FAILED",
    404: "NOT_FOUND",
    408: "UNAVAILABLE",
    409: "CONFLICT",
    429: "RATE_LIMITED",
    500: "SERVER_ERROR",
    502: "UNAVAILABLE",
    503: "UNAVAILABLE",
    504: "UNAVAILABLE",
}
RETRYABLE_STATUS_CODES = {408, 425, 429, 500, 502, 503, 504}
REQUIRED_RUNTIME_ENV = ["TARGET_URL"]
SESSIONS: dict[str, dict[str, Any]] = {}


def _utc_now() -> datetime:
    return datetime.now(UTC)


def _isoformat(dt: datetime) -> str:
    return dt.isoformat().replace("+00:00", "Z")


def _prune_sessions() -> None:
    if not SESSIONS:
        return
    now = _utc_now()
    expired_ids: list[str] = []
    for session_id, session in SESSIONS.items():
        expires_at = session.get("expires_at")
        if isinstance(expires_at, str):
            expiry = datetime.fromisoformat(expires_at.replace("Z", "+00:00"))
            if expiry <= now:
                expired_ids.append(session_id)
    for session_id in expired_ids:
        SESSIONS.pop(session_id, None)


def _ensure_session(tool_name: str) -> tuple[str | None, dict[str, Any] | None]:
    metadata = TOOL_METADATA.get(tool_name, {})
    if not metadata.get("requires_session"):
        return None, None

    _prune_sessions()
    if len(SESSIONS) >= SETTINGS.max_sessions:
        raise RuntimeError(
            f"Session capacity exceeded: {len(SESSIONS)} active sessions, max {SETTINGS.max_sessions}"
        )

    created_at = _utc_now()
    expires_at = created_at.timestamp() + SETTINGS.session_ttl_seconds
    session_id = f"sess_{uuid.uuid4().hex[:12]}"
    session = {
        "session_id": session_id,
        "tool_name": tool_name,
        "created_at": _isoformat(created_at),
        "expires_at": _isoformat(datetime.fromtimestamp(expires_at, tz=UTC)),
        "workflow_states": RUNTIME_STATE.get("workflow_states", {}),
        "entities": RUNTIME_STATE.get("session_entities", []),
    }
    SESSIONS[session_id] = session
    return session_id, session


def _runtime_requirements() -> dict[str, bool]:
    return {
        key: bool(os.environ.get(key))
        for key in REQUIRED_RUNTIME_ENV
    }


def _readiness_summary() -> dict[str, int]:
    counts: dict[str, int] = {}
    for metadata in TOOL_METADATA.values():
        readiness = str(metadata.get("readiness", "unknown"))
        counts[readiness] = counts.get(readiness, 0) + 1
    return counts


def _operational_snapshot() -> dict[str, Any]:
    _prune_sessions()
    return {
        "service": "http://127.0.0.1:43987",
        "tool_count": len(TOOL_METADATA),
        "route_count": len(ROUTE_MAP.get("routes", {})),
        "readiness_summary": _readiness_summary(),
        "active_sessions": len(SESSIONS),
        "approval_bypass_enabled": SETTINGS.allow_unsafe_automation,
        "browser_headless": SETTINGS.browser_headless,
        "required_env": _runtime_requirements(),
    }


def _health_payload() -> dict[str, Any]:
    return {
        "status": "ok",
        "timestamp": _isoformat(_utc_now()),
        "snapshot": _operational_snapshot(),
    }


def _readiness_payload() -> dict[str, Any]:
    required_env = _runtime_requirements()
    missing = [key for key, present in required_env.items() if not present]
    browser_runtime_available = True
    try:
        import playwright.async_api  # noqa: F401
    except Exception:
        browser_runtime_available = False

    return {
        "status": "ready" if not missing else "degraded",
        "missing_required_env": missing,
        "browser_runtime_available": browser_runtime_available,
        "snapshot": _operational_snapshot(),
    }


@mcp.tool()
async def healthcheck() -> dict:
    """Return a lightweight health snapshot for the generated runtime."""
    return _health_payload()


@mcp.tool()
async def readiness() -> dict:
    """Return runtime readiness information and configuration posture."""
    return _readiness_payload()


@mcp.tool()
async def runtime_snapshot() -> dict:
    """Return operational metadata for debugging and deployment inspection."""
    return {
        "settings": asdict(SETTINGS),
        "tool_metadata": TOOL_METADATA,
        "runtime_state": RUNTIME_STATE,
        "snapshot": _operational_snapshot(),
    }


def _check_approval(tool_name: str, params: dict[str, Any]) -> dict[str, Any] | None:
    policy = APPROVAL_POLICY.get(tool_name, {})
    if not policy.get("require_confirmation"):
        return None
    if SETTINGS.allow_unsafe_automation:
        return None

    return {
        "error": "PAYMENT_REQUIRED",
        "message": "Human confirmation is required before executing this tool.",
        "tool": tool_name,
        "approval_required": True,
        "policy_notes": policy.get("notes", []),
        "recovery": "Set AGENT_SEE_ALLOW_UNSAFE_AUTOMATION=true only in explicitly approved, controlled environments.",
        "params_preview": params,
    }


async def _sleep_before_retry(attempt: int, tool_name: str, reason: str) -> None:
    delay = SETTINGS.retry_backoff_seconds * (2 ** max(0, attempt - 1))
    logger.warning(
        "Retrying tool %s after attempt %s due to transient failure: %s",
        tool_name,
        attempt,
        reason,
    )
    if delay > 0:
        await asyncio.sleep(delay)


def _error_envelope(
    tool_name: str,
    error: str,
    message: str,
    *,
    status: int | None = None,
    attempts: int | None = None,
) -> dict[str, Any]:
    envelope: dict[str, Any] = {
        "error": error,
        "message": message,
        "operational_status": TOOL_METADATA.get(tool_name, {}),
    }
    if status is not None:
        envelope["status"] = status
    if attempts is not None:
        envelope["attempts"] = attempts
    return envelope


async def execute_tool(
    tool_name: str,
    params: dict[str, Any],
    backend: ExecutionBackend,
) -> dict[str, Any]:
    """Execute a tool against the original site with bounded operational behavior."""
    approval_result = _check_approval(tool_name, params)
    if approval_result is not None:
        return approval_result

    try:
        session_id, session = _ensure_session(tool_name)
    except RuntimeError as exc:
        return _error_envelope(tool_name, "UNAVAILABLE", str(exc))

    if backend == ExecutionBackend.API:
        result = await _execute_via_api(tool_name, params)
    elif backend == ExecutionBackend.BROWSER:
        result = await _execute_via_browser(tool_name, params)
    else:
        result = await _execute_via_hybrid(tool_name, params)

    metadata = TOOL_METADATA.get(tool_name, {})
    result.setdefault("_tool", tool_name)
    result.setdefault("_readiness", metadata.get("readiness", "structural_only"))
    result.setdefault("_verification", metadata.get("verification", "structural"))
    if session_id:
        result.setdefault("session_id", session_id)
        result.setdefault("session", session)
    return result


async def _execute_via_hybrid(tool_name: str, params: dict[str, Any]) -> dict[str, Any]:
    api_result = await _execute_via_api(tool_name, params)
    if "error" not in api_result:
        return api_result
    logger.warning(
        "Hybrid execution falling back to browser for %s after API failure: %s",
        tool_name,
        api_result.get("message", api_result.get("error", "unknown error")),
    )
    browser_result = await _execute_via_browser(tool_name, params)
    browser_result.setdefault("_fallback_from", "api")
    return browser_result


async def _execute_via_api(tool_name: str, params: dict[str, Any]) -> dict[str, Any]:
    routes = ROUTE_MAP.get("routes", {})
    route = routes.get(tool_name)
    if not route:
        return _error_envelope(tool_name, "NOT_FOUND", f"No API route for {tool_name}")

    base_url = ROUTE_MAP.get("base_url", SETTINGS.target_url)
    method = route["method"]
    path = route["path"]

    for param_name in route.get("path_params", []):
        value = params.get(param_name, "")
        path = path.replace(" + param_name + ", str(value))

    url = f"{base_url}{path}"
    query = {key: params[key] for key in route.get("query_params", []) if key in params}
    body_params = route.get("body_params", [])
    body = (
        {key: params[key] for key in body_params if key in params}
        if body_params
        else None
    )

    headers = {
        "Accept": "application/json",
        "User-Agent": "AgentSee/0.1 (MCP Executor)",
        **AUTH_HEADERS,
    }
    if body is not None:
        headers["Content-Type"] = route.get("content_type", "application/json")

    for attempt in range(1, SETTINGS.api_max_retries + 2):
        try:
            async with httpx.AsyncClient(timeout=SETTINGS.request_timeout_seconds) as client:
                response = await client.request(
                    method=method,
                    url=url,
                    params=query or None,
                    json=body,
                    headers=headers,
                )
        except httpx.TimeoutException as exc:
            if attempt <= SETTINGS.api_max_retries:
                await _sleep_before_retry(attempt, tool_name, str(exc))
                continue
            return _error_envelope(
                tool_name,
                "UNAVAILABLE",
                f"Request timed out after {attempt} attempt(s)",
                attempts=attempt,
            )
        except httpx.TransportError as exc:
            if attempt <= SETTINGS.api_max_retries:
                await _sleep_before_retry(attempt, tool_name, str(exc))
                continue
            return _error_envelope(
                tool_name,
                "UNAVAILABLE",
                f"Transport failure after {attempt} attempt(s): {exc}",
                attempts=attempt,
            )

        if response.status_code in RETRYABLE_STATUS_CODES and attempt <= SETTINGS.api_max_retries:
            await _sleep_before_retry(attempt, tool_name, f"HTTP {response.status_code}")
            continue

        if response.status_code >= 400:
            message = f"HTTP {response.status_code}"
            try:
                error_body = response.json()
                if isinstance(error_body, dict):
                    message = error_body.get("message", error_body.get("error", message))
            except Exception:
                message = response.text[:200] if response.text else message
            return _error_envelope(
                tool_name,
                STATUS_ERROR_MAP.get(response.status_code, "SERVER_ERROR"),
                str(message),
                status=response.status_code,
                attempts=attempt,
            )

        content_type = response.headers.get("content-type", "")
        if "json" in content_type:
            data = response.json()
            if isinstance(data, list):
                return {"items": data, "count": len(data), "_attempts": attempt, "_transport": "api"}
            if isinstance(data, dict):
                data.setdefault("_attempts", attempt)
                data.setdefault("_transport", "api")
                return data
            return {"result": data, "_attempts": attempt, "_transport": "api"}

        return {
            "status": "success",
            "status_code": response.status_code,
            "body": response.text[:2000],
            "_attempts": attempt,
            "_transport": "api",
        }

    return _error_envelope(tool_name, "SERVER_ERROR", "Unhandled API execution state")


async def _execute_via_browser(tool_name: str, params: dict[str, Any]) -> dict[str, Any]:
    try:
        from agent_see.execution.browser_executor import (
            BrowserExecutionError,
            BrowserExecutor,
            FormMapping,
            ScrapingRule,
        )
    except ImportError:
        return _error_envelope(
            tool_name,
            "UNAVAILABLE",
            "Browser runtime dependencies are not available",
        )

    form_mappings = [FormMapping(**item) for item in FORM_MAPPINGS]
    scraping_rules = [ScrapingRule(**item) for item in SCRAPING_RULES]
    executor = BrowserExecutor(
        base_url=SETTINGS.target_url,
        form_mappings=form_mappings,
        scraping_rules=scraping_rules,
        headless=SETTINGS.browser_headless,
        timeout_ms=SETTINGS.browser_timeout_ms,
        max_retries=SETTINGS.browser_max_retries,
        retry_backoff_seconds=SETTINGS.retry_backoff_seconds,
    )

    try:
        result = await executor.execute(tool_name, params)
        result.setdefault("operational_status", TOOL_METADATA.get(tool_name, {}))
        return result
    except BrowserExecutionError as exc:
        return _error_envelope(tool_name, exc.code, exc.message)
    except Exception as exc:
        return _error_envelope(tool_name, "SERVER_ERROR", str(exc))


# === Generated Tools ===

@mcp.tool()
async def list_products(category: str = None, limit: int = 20, page: int = 1, query: str = None, min_price: float = None, max_price: float = None) -> dict:
    """List all products in the bakery catalog"""
    params = {}
    params["category"] = category
    params["limit"] = limit
    params["page"] = page
    params["query"] = query
    params["min_price"] = min_price
    params["max_price"] = max_price
    return await execute_tool("list_products", params, ExecutionBackend.API)


@mcp.tool()
async def get_product_details(productId: str, product_id: str) -> dict:
    """Get full details for a specific product"""
    params = {}
    params["productId"] = productId
    params["product_id"] = product_id
    return await execute_tool("get_product_details", params, ExecutionBackend.API)


@mcp.tool()
async def get_cart() -> dict:
    """Get current shopping cart contents"""
    params = {}
    pass
    return await execute_tool("get_cart", params, ExecutionBackend.API)


@mcp.tool()
async def add_to_cart(product_id: str, quantity: int, variant_id: str = None) -> dict:
    """Add a product to the shopping cart"""
    params = {}
    params["product_id"] = product_id
    params["quantity"] = quantity
    params["variant_id"] = variant_id
    return await execute_tool("add_to_cart", params, ExecutionBackend.API)


@mcp.tool()
async def submit_checkout(shipping_address: dict, email: str, shipping_method: str = None, full_name: str, address: str, zip_code: str) -> dict:
    """Initiate checkout - returns payment URL for confirmation"""
    params = {}
    params["shipping_address"] = shipping_address
    params["email"] = email
    params["shipping_method"] = shipping_method
    params["full_name"] = full_name
    params["address"] = address
    params["zip_code"] = zip_code
    return await execute_tool("submit_checkout", params, ExecutionBackend.API)


@mcp.tool()
async def get_order_status(orderId: str, order_id: str) -> dict:
    """Get order status and tracking info"""
    params = {}
    params["orderId"] = orderId
    params["order_id"] = order_id
    return await execute_tool("get_order_status", params, ExecutionBackend.API)


@mcp.tool()
async def search_items(query: str = None) -> dict:
    """Search for items on the site"""
    params = {}
    params["query"] = query
    return await execute_tool("search_items", params, ExecutionBackend.BROWSER)


@mcp.tool()
async def send_message(sender_name: str, sender_email: str, subject: str, body: str) -> dict:
    """Send a message to the business"""
    params = {}
    params["sender_name"] = sender_name
    params["sender_email"] = sender_email
    params["subject"] = subject
    params["body"] = body
    return await execute_tool("send_message", params, ExecutionBackend.BROWSER)


@mcp.tool()
async def get_business_info() -> dict:
    """Get business contact information, hours, and location"""
    params = {}
    pass
    return await execute_tool("get_business_info", params, ExecutionBackend.BROWSER)


@mcp.tool()
async def check_inventory(product_id: str, variant_id: str = None) -> dict:
    """Check real-time stock status for a product variant"""
    params = {}
    params["product_id"] = product_id
    params["variant_id"] = variant_id
    return await execute_tool("check_inventory", params, ExecutionBackend.HYBRID)


@mcp.tool()
async def remove_from_cart(product_id: str, variant_id: str = None) -> dict:
    """Remove a product from the shopping cart"""
    params = {}
    params["product_id"] = product_id
    params["variant_id"] = variant_id
    return await execute_tool("remove_from_cart", params, ExecutionBackend.HYBRID)


@mcp.tool()
async def apply_coupon(code: str) -> dict:
    """Apply a coupon or discount code to the cart"""
    params = {}
    params["code"] = code
    return await execute_tool("apply_coupon", params, ExecutionBackend.HYBRID)


@mcp.tool()
async def calculate_shipping(zip_code: str, country: str = 'US') -> dict:
    """Calculate shipping options and costs for delivery address"""
    params = {}
    params["zip_code"] = zip_code
    params["country"] = country
    return await execute_tool("calculate_shipping", params, ExecutionBackend.HYBRID)


@mcp.tool()
async def initiate_return(order_id: str, item_ids: list, reason: str) -> dict:
    """Start a return or refund request for an order"""
    params = {}
    params["order_id"] = order_id
    params["item_ids"] = item_ids
    params["reason"] = reason
    return await execute_tool("initiate_return", params, ExecutionBackend.HYBRID)


if __name__ == "__main__":
    logger.info(
        "Starting MCP runtime on port %s for %s",
        SETTINGS.port,
        SETTINGS.target_url,
    )
    mcp.run()
