"""Auto-generated MCP server for http://127.0.0.1:33235.

Generated by Agent-See v0.1.0
Capabilities: 14
Source: http://127.0.0.1:33235

Important: this server distinguishes interface generation from runtime readiness.
Approval-gated tools may require explicit human confirmation before execution.
"""

from __future__ import annotations

import logging
import os
import uuid
from datetime import datetime
from enum import Enum

import httpx
from mcp.server.fastmcp import FastMCP

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ExecutionBackend(str, Enum):
    API = "api"
    BROWSER = "browser"
    HYBRID = "hybrid"


mcp = FastMCP(
    "http://127.0.0.1:33235",
    description="Agent-optimized interface for http://127.0.0.1:33235",
)

TARGET_URL = os.environ.get("TARGET_URL", "http://127.0.0.1:33235")
APPROVAL_BYPASS = os.environ.get("AGENT_SEE_ALLOW_UNSAFE_AUTOMATION", "false").lower() == "true"

ROUTE_MAP = {
  "base_url": "http://127.0.0.1:33235",
  "routes": {
    "list_products": {
      "method": "GET",
      "path": "/products",
      "path_params": [],
      "query_params": [
        "category",
        "limit",
        "page",
        "query",
        "min_price",
        "max_price"
      ],
      "body_params": [],
      "content_type": "application/json"
    },
    "get_product_details": {
      "method": "GET",
      "path": "/products/{productId}",
      "path_params": [
        "productId"
      ],
      "query_params": [
        "product_id"
      ],
      "body_params": [],
      "content_type": "application/json"
    },
    "get_cart": {
      "method": "GET",
      "path": "/cart",
      "path_params": [],
      "query_params": [],
      "body_params": [],
      "content_type": "application/json"
    },
    "add_to_cart": {
      "method": "POST",
      "path": "/cart/items",
      "path_params": [],
      "query_params": [],
      "body_params": [
        "product_id",
        "quantity",
        "variant_id"
      ],
      "content_type": "application/json"
    },
    "submit_checkout": {
      "method": "POST",
      "path": "/checkout",
      "path_params": [],
      "query_params": [],
      "body_params": [
        "shipping_address",
        "email",
        "shipping_method",
        "full_name",
        "address",
        "zip_code"
      ],
      "content_type": "application/json"
    },
    "get_order_status": {
      "method": "GET",
      "path": "/orders/{orderId}",
      "path_params": [
        "orderId"
      ],
      "query_params": [
        "order_id"
      ],
      "body_params": [],
      "content_type": "application/json"
    }
  }
}
APPROVAL_POLICY = {
  "list_products": {
    "require_confirmation": false,
    "notes": [
      "Execution path is grounded in a discovered API route, but it has not been marked as live-verified by the generator.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context."
    ]
  },
  "get_product_details": {
    "require_confirmation": false,
    "notes": [
      "Execution path is grounded in a discovered API route, but it has not been marked as live-verified by the generator.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context."
    ]
  },
  "get_cart": {
    "require_confirmation": false,
    "notes": [
      "Execution path is grounded in a discovered API route, but it has not been marked as live-verified by the generator.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context."
    ]
  },
  "add_to_cart": {
    "require_confirmation": false,
    "notes": [
      "Execution path is grounded in a discovered API route, but it has not been marked as live-verified by the generator.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context."
    ]
  },
  "submit_checkout": {
    "require_confirmation": true,
    "notes": [
      "Execution path is grounded in a discovered API route, but it has not been marked as live-verified by the generator.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context.",
      "Human confirmation should be required before executing irreversible, payment-related, or identity-sensitive actions."
    ]
  },
  "get_order_status": {
    "require_confirmation": false,
    "notes": [
      "Execution path is grounded in a discovered API route, but it has not been marked as live-verified by the generator.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context."
    ]
  },
  "send_message": {
    "require_confirmation": true,
    "notes": [
      "Browser execution is generated from discovered DOM or network evidence and may require site-specific selector hardening.",
      "Human confirmation should be required before executing irreversible, payment-related, or identity-sensitive actions."
    ]
  },
  "search_items": {
    "require_confirmation": true,
    "notes": [
      "Browser execution is generated from discovered DOM or network evidence and may require site-specific selector hardening.",
      "Human confirmation should be required before executing irreversible, payment-related, or identity-sensitive actions."
    ]
  },
  "get_business_info": {
    "require_confirmation": false,
    "notes": [
      "Browser execution is generated from discovered DOM or network evidence and may require site-specific selector hardening."
    ]
  },
  "check_inventory": {
    "require_confirmation": false,
    "notes": [
      "This capability is currently represented structurally and may need a site-specific executor before production use."
    ]
  },
  "remove_from_cart": {
    "require_confirmation": false,
    "notes": [
      "This capability is currently represented structurally and may need a site-specific executor before production use.",
      "This tool participates in stateful execution and may depend on cookies, session continuity, or persisted workflow context."
    ]
  },
  "apply_coupon": {
    "require_confirmation": false,
    "notes": [
      "This capability is currently represented structurally and may need a site-specific executor before production use."
    ]
  },
  "calculate_shipping": {
    "require_confirmation": false,
    "notes": [
      "This capability is currently represented structurally and may need a site-specific executor before production use."
    ]
  },
  "initiate_return": {
    "require_confirmation": false,
    "notes": [
      "This capability is currently represented structurally and may need a site-specific executor before production use."
    ]
  }
}
TOOL_METADATA = {
  "list_products": {
    "backend": "api",
    "readiness": "route_mapped",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "none"
  },
  "get_product_details": {
    "backend": "api",
    "readiness": "route_mapped",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "none"
  },
  "get_cart": {
    "backend": "api",
    "readiness": "route_mapped",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "none"
  },
  "add_to_cart": {
    "backend": "api",
    "readiness": "route_mapped",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "none"
  },
  "submit_checkout": {
    "backend": "api",
    "readiness": "route_mapped",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "confirmation_required"
  },
  "get_order_status": {
    "backend": "api",
    "readiness": "route_mapped",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "none"
  },
  "send_message": {
    "backend": "browser",
    "readiness": "generated_browser",
    "verification": "inferred",
    "requires_session": false,
    "approval_requirement": "confirmation_required"
  },
  "search_items": {
    "backend": "browser",
    "readiness": "generated_browser",
    "verification": "inferred",
    "requires_session": false,
    "approval_requirement": "confirmation_required"
  },
  "get_business_info": {
    "backend": "browser",
    "readiness": "generated_browser",
    "verification": "inferred",
    "requires_session": false,
    "approval_requirement": "none"
  },
  "check_inventory": {
    "backend": "hybrid",
    "readiness": "structural_only",
    "verification": "structural",
    "requires_session": false,
    "approval_requirement": "none"
  },
  "remove_from_cart": {
    "backend": "hybrid",
    "readiness": "structural_only",
    "verification": "structural",
    "requires_session": true,
    "approval_requirement": "none"
  },
  "apply_coupon": {
    "backend": "hybrid",
    "readiness": "structural_only",
    "verification": "structural",
    "requires_session": false,
    "approval_requirement": "none"
  },
  "calculate_shipping": {
    "backend": "hybrid",
    "readiness": "structural_only",
    "verification": "structural",
    "requires_session": false,
    "approval_requirement": "none"
  },
  "initiate_return": {
    "backend": "hybrid",
    "readiness": "structural_only",
    "verification": "structural",
    "requires_session": false,
    "approval_requirement": "none"
  }
}
FORM_MAPPINGS = [
  {
    "tool_name": "send_message",
    "page_url": "http://127.0.0.1:33235/contact",
    "form_selector": "form",
    "field_map": {
      "sender_name": "[name='sender_name']",
      "sender_email": "[name='sender_email']",
      "subject": "[name='subject']",
      "body": "[name='body']"
    },
    "submit_selector": "button[type=submit], input[type=submit]",
    "wait_for": "",
    "extract_selectors": {}
  },
  {
    "tool_name": "search_items",
    "page_url": "http://127.0.0.1:33235/products",
    "form_selector": "form",
    "field_map": {
      "query": "[name='query']"
    },
    "submit_selector": "button[type=submit], input[type=submit]",
    "wait_for": "",
    "extract_selectors": {}
  },
  {
    "tool_name": "get_business_info",
    "page_url": "http://127.0.0.1:33235/about",
    "form_selector": "form",
    "field_map": {},
    "submit_selector": "button[type=submit], input[type=submit]",
    "wait_for": "",
    "extract_selectors": {}
  }
]
SCRAPING_RULES = [
  {
    "tool_name": "get_business_info",
    "page_url": "http://127.0.0.1:33235/about",
    "item_selector": "body",
    "field_selectors": {
      "text": "body"
    },
    "pagination_selector": ""
  }
]
RUNTIME_STATE = {
  "states": {
    "browsing": [
      "cart_review"
    ],
    "cart_review": [
      "checkout_ready",
      "browsing"
    ],
    "checkout_ready": [
      "payment_pending",
      "cart_review"
    ],
    "payment_pending": [
      "order_tracking"
    ],
    "order_tracking": []
  },
  "workflow_states": {
    "purchase_flow": [
      "browsing",
      "cart_review",
      "checkout_ready",
      "payment_pending",
      "order_tracking"
    ]
  },
  "session_entities": [
    "cart_session"
  ],
  "operational_notes": [
    "This state model is inferred from discovered capabilities and workflow order.",
    "It is intended to scaffold runtime continuity and should not be interpreted as a proof of live production behavior.",
    "E-commerce flows are modeled with an in-memory cart-style session unless the generated server is integrated with durable storage."
  ]
}

AUTH_HEADERS = {}
if os.environ.get("API_KEY"):
    AUTH_HEADERS["Authorization"] = f"Bearer {os.environ['API_KEY']}"
if os.environ.get("API_KEY_HEADER") and os.environ.get("API_KEY_VALUE"):
    AUTH_HEADERS[os.environ["API_KEY_HEADER"]] = os.environ["API_KEY_VALUE"]

STATUS_ERROR_MAP = {
    400: "INVALID_PARAM",
    401: "AUTH_FAILED",
    403: "AUTH_FAILED",
    404: "NOT_FOUND",
    409: "CONFLICT",
    429: "RATE_LIMITED",
    402: "PAYMENT_REQUIRED",
    503: "UNAVAILABLE",
}

SESSIONS: dict[str, dict] = {}


def _ensure_session(tool_name: str) -> tuple[str | None, dict | None]:
    metadata = TOOL_METADATA.get(tool_name, {})
    if not metadata.get("requires_session"):
        return None, None

    session_id = f"sess_{uuid.uuid4().hex[:12]}"
    session = {
        "session_id": session_id,
        "tool_name": tool_name,
        "created_at": datetime.utcnow().isoformat() + "Z",
        "workflow_states": RUNTIME_STATE.get("workflow_states", {}),
        "entities": RUNTIME_STATE.get("session_entities", []),
    }
    SESSIONS[session_id] = session
    return session_id, session


def _check_approval(tool_name: str, params: dict) -> dict | None:
    policy = APPROVAL_POLICY.get(tool_name, {})
    if not policy.get("require_confirmation"):
        return None
    if APPROVAL_BYPASS:
        return None

    return {
        "error": "PAYMENT_REQUIRED",
        "message": "Human confirmation is required before executing this tool.",
        "tool": tool_name,
        "approval_required": True,
        "policy_notes": policy.get("notes", []),
        "recovery": "Set AGENT_SEE_ALLOW_UNSAFE_AUTOMATION=true only in explicitly approved, controlled environments.",
        "params_preview": params,
    }


async def execute_tool(
    tool_name: str,
    params: dict,
    backend: ExecutionBackend,
) -> dict:
    """Execute a tool against the original site.

    Routes to API executor or browser executor based on backend type and enforces
    approval gating for sensitive operations.
    """
    approval_result = _check_approval(tool_name, params)
    if approval_result is not None:
        return approval_result

    session_id, session = _ensure_session(tool_name)

    if backend == ExecutionBackend.API:
        result = await _execute_via_api(tool_name, params)
    elif backend == ExecutionBackend.BROWSER:
        result = await _execute_via_browser(tool_name, params)
    else:
        try:
            result = await _execute_via_api(tool_name, params)
        except Exception:
            result = await _execute_via_browser(tool_name, params)

    metadata = TOOL_METADATA.get(tool_name, {})
    result.setdefault("_tool", tool_name)
    result.setdefault("_readiness", metadata.get("readiness", "structural_only"))
    result.setdefault("_verification", metadata.get("verification", "structural"))
    if session_id:
        result.setdefault("session_id", session_id)
        result.setdefault("session", session)
    return result


async def _execute_via_api(tool_name: str, params: dict) -> dict:
    """Execute a tool via direct API call to the original site."""
    routes = ROUTE_MAP.get("routes", {})
    route = routes.get(tool_name)

    if not route:
        return {
            "error": "NOT_FOUND",
            "message": f"No API route for {tool_name}",
            "operational_status": TOOL_METADATA.get(tool_name, {}),
        }

    base_url = ROUTE_MAP.get("base_url", TARGET_URL)
    method = route["method"]
    path = route["path"]

    for param_name in route.get("path_params", []):
        value = params.get(param_name, "")
        path = path.replace(" + param_name + ", str(value))

    url = f"{base_url}{path}"
    query = {k: params[k] for k in route.get("query_params", []) if k in params}

    body = None
    body_params = route.get("body_params", [])
    if body_params:
        body = {k: params[k] for k in body_params if k in params}

    headers = {
        "Accept": "application/json",
        "User-Agent": "AgentSee/0.1 (MCP Executor)",
        **AUTH_HEADERS,
    }
    if body is not None:
        headers["Content-Type"] = route.get("content_type", "application/json")

    logger.info(f"Executing {method} {url}")

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.request(
            method=method,
            url=url,
            params=query or None,
            json=body,
            headers=headers,
        )

    if response.status_code >= 400:
        error_code = STATUS_ERROR_MAP.get(response.status_code, "SERVER_ERROR")
        message = f"HTTP {response.status_code}"
        try:
            error_body = response.json()
            if isinstance(error_body, dict):
                message = error_body.get("message", error_body.get("error", message))
        except Exception:
            message = response.text[:200] if response.text else message
        return {
            "error": error_code,
            "message": str(message),
            "status": response.status_code,
            "operational_status": TOOL_METADATA.get(tool_name, {}),
        }

    content_type = response.headers.get("content-type", "")
    if "json" in content_type:
        data = response.json()
        if isinstance(data, list):
            return {"items": data, "count": len(data)}
        if isinstance(data, dict):
            return data
        return {"result": data}

    return {
        "status": "success",
        "status_code": response.status_code,
        "body": response.text[:2000],
    }


async def _execute_via_browser(tool_name: str, params: dict) -> dict:
    """Execute a tool via Playwright browser automation scaffolding."""
    try:
        from agent_see.execution.browser_executor import (
            BrowserExecutionError,
            BrowserExecutor,
            FormMapping,
            ScrapingRule,
        )
    except ImportError:
        return {"error": "UNAVAILABLE", "message": "Browser runtime dependencies are not available"}

    form_mappings = [FormMapping(**item) for item in FORM_MAPPINGS]
    scraping_rules = [ScrapingRule(**item) for item in SCRAPING_RULES]
    executor = BrowserExecutor(
        base_url=TARGET_URL,
        form_mappings=form_mappings,
        scraping_rules=scraping_rules,
        headless=True,
    )

    try:
        result = await executor.execute(tool_name, params)
        result.setdefault("operational_status", TOOL_METADATA.get(tool_name, {}))
        return result
    except BrowserExecutionError as exc:
        return {
            "error": exc.code,
            "message": exc.message,
            "operational_status": TOOL_METADATA.get(tool_name, {}),
        }
    except Exception as exc:
        return {
            "error": "SERVER_ERROR",
            "message": str(exc),
            "operational_status": TOOL_METADATA.get(tool_name, {}),
        }


# === Generated Tools ===

@mcp.tool()
async def list_products(category: str = None, limit: int = 20, page: int = 1, query: str = None, min_price: float = None, max_price: float = None) -> dict:
    """List all products in the bakery catalog"""
    params = {}
    params["category"] = category
    params["limit"] = limit
    params["page"] = page
    params["query"] = query
    params["min_price"] = min_price
    params["max_price"] = max_price
    return await execute_tool("list_products", params, ExecutionBackend.API)


@mcp.tool()
async def get_product_details(productId: str, product_id: str) -> dict:
    """Get full details for a specific product"""
    params = {}
    params["productId"] = productId
    params["product_id"] = product_id
    return await execute_tool("get_product_details", params, ExecutionBackend.API)


@mcp.tool()
async def get_cart() -> dict:
    """Get current shopping cart contents"""
    params = {}
    pass
    return await execute_tool("get_cart", params, ExecutionBackend.API)


@mcp.tool()
async def add_to_cart(product_id: str, quantity: int, variant_id: str = None) -> dict:
    """Add a product to the shopping cart"""
    params = {}
    params["product_id"] = product_id
    params["quantity"] = quantity
    params["variant_id"] = variant_id
    return await execute_tool("add_to_cart", params, ExecutionBackend.API)


@mcp.tool()
async def submit_checkout(shipping_address: dict, email: str, shipping_method: str = None, full_name: str, address: str, zip_code: str) -> dict:
    """Initiate checkout - returns payment URL for confirmation"""
    params = {}
    params["shipping_address"] = shipping_address
    params["email"] = email
    params["shipping_method"] = shipping_method
    params["full_name"] = full_name
    params["address"] = address
    params["zip_code"] = zip_code
    return await execute_tool("submit_checkout", params, ExecutionBackend.API)


@mcp.tool()
async def get_order_status(orderId: str, order_id: str) -> dict:
    """Get order status and tracking info"""
    params = {}
    params["orderId"] = orderId
    params["order_id"] = order_id
    return await execute_tool("get_order_status", params, ExecutionBackend.API)


@mcp.tool()
async def send_message(sender_name: str, sender_email: str, subject: str, body: str) -> dict:
    """Send a message to the business"""
    params = {}
    params["sender_name"] = sender_name
    params["sender_email"] = sender_email
    params["subject"] = subject
    params["body"] = body
    return await execute_tool("send_message", params, ExecutionBackend.BROWSER)


@mcp.tool()
async def search_items(query: str = None) -> dict:
    """Search for items on the site"""
    params = {}
    params["query"] = query
    return await execute_tool("search_items", params, ExecutionBackend.BROWSER)


@mcp.tool()
async def get_business_info() -> dict:
    """Get business contact information, hours, and location"""
    params = {}
    pass
    return await execute_tool("get_business_info", params, ExecutionBackend.BROWSER)


@mcp.tool()
async def check_inventory(product_id: str, variant_id: str = None) -> dict:
    """Check real-time stock status for a product variant"""
    params = {}
    params["product_id"] = product_id
    params["variant_id"] = variant_id
    return await execute_tool("check_inventory", params, ExecutionBackend.HYBRID)


@mcp.tool()
async def remove_from_cart(product_id: str, variant_id: str = None) -> dict:
    """Remove a product from the shopping cart"""
    params = {}
    params["product_id"] = product_id
    params["variant_id"] = variant_id
    return await execute_tool("remove_from_cart", params, ExecutionBackend.HYBRID)


@mcp.tool()
async def apply_coupon(code: str) -> dict:
    """Apply a coupon or discount code to the cart"""
    params = {}
    params["code"] = code
    return await execute_tool("apply_coupon", params, ExecutionBackend.HYBRID)


@mcp.tool()
async def calculate_shipping(zip_code: str, country: str = 'US') -> dict:
    """Calculate shipping options and costs for delivery address"""
    params = {}
    params["zip_code"] = zip_code
    params["country"] = country
    return await execute_tool("calculate_shipping", params, ExecutionBackend.HYBRID)


@mcp.tool()
async def initiate_return(order_id: str, item_ids: list, reason: str) -> dict:
    """Start a return or refund request for an order"""
    params = {}
    params["order_id"] = order_id
    params["item_ids"] = item_ids
    params["reason"] = reason
    return await execute_tool("initiate_return", params, ExecutionBackend.HYBRID)


if __name__ == "__main__":
    mcp.run()
