"""Generate deployable MCP server packages for converted Agent-See interfaces.

The generated runtime is intentionally explicit about operational posture. It
includes grounded route mappings where possible, browser automation scaffolding
for DOM-discovered capabilities, approval gates for sensitive actions, and a
bounded runtime model with health and readiness inspection surfaces.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path

from agent_see.execution.browser_executor import (
    build_form_mappings_from_graph,
    build_scraping_rules_from_graph,
)
from agent_see.execution.route_map import RouteMap, build_route_map
from agent_see.models.capability import CapabilityGraph
from agent_see.models.schema import ToolSchema

logger = logging.getLogger(__name__)


def _generate_server_py(
    graph: CapabilityGraph,
    tool_schemas: list[ToolSchema],
    route_map: RouteMap,
) -> str:
    """Generate the main MCP runtime with operational guardrails."""
    tool_registrations: list[str] = []

    for schema in tool_schemas:
        func_name = schema.name
        params_str = ", ".join(
            f'{param.name}: {_python_type(param.type)}'
            + (f' = {repr(param.default)}' if not param.required else "")
            for param in schema.parameters
        )
        param_assignments = "\n    ".join(
            f'params["{param.name}"] = {param.name}' for param in schema.parameters
        )

        if not params_str:
            params_str = ""
            param_assignments = "pass"

        tool_registrations.append(
            f'''
@mcp.tool()
async def {func_name}({params_str}) -> dict:
    """{schema.description}"""
    params = {{}}
    {param_assignments}
    return await execute_tool("{func_name}", params, ExecutionBackend.{schema.execution_backend.name})
'''
        )

    route_map_json = json.dumps(route_map.to_dict(), indent=2)
    approval_map_json = json.dumps(
        {
            schema.name: {
                "require_confirmation": (
                    schema.approval_requirement.value == "confirmation_required"
                ),
                "notes": schema.operational_notes,
            }
            for schema in tool_schemas
        },
        indent=2,
    )
    tool_metadata_json = json.dumps(
        {
            schema.name: {
                "backend": schema.execution_backend.value,
                "readiness": schema.execution_readiness.value,
                "verification": schema.verification_status.value,
                "requires_session": schema.requires_session,
                "approval_requirement": schema.approval_requirement.value,
                "errors": [error.model_dump() for error in schema.errors],
            }
            for schema in tool_schemas
        },
        indent=2,
    )
    form_mappings_json = json.dumps(
        [mapping.__dict__ for mapping in build_form_mappings_from_graph(graph)],
        indent=2,
    )
    scraping_rules_json = json.dumps(
        [rule.__dict__ for rule in build_scraping_rules_from_graph(graph)],
        indent=2,
    )
    runtime_state_json = json.dumps(
        {
            "states": graph.state_model.states,
            "workflow_states": graph.state_model.workflow_states,
            "session_entities": graph.state_model.session_entities,
            "operational_notes": graph.state_model.operational_notes,
        },
        indent=2,
    )
    tools_code = "\n".join(tool_registrations)
    runtime_path_placeholder_expr = 'f"{{{param_name}}}"'

    return f'''"""Auto-generated MCP server for {graph.source_url or 'SaaS application'}.

Generated by Agent-See v0.1.0
Capabilities: {graph.capability_count}
Source: {graph.source_url or 'N/A'}

Important: this runtime separates interface generation from operational
readiness. It includes bounded retries, approval gates, and session limits,
but still requires operator-controlled credentials, monitoring, and deployment
policy review.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import time
import uuid
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from enum import Enum
from typing import Any

import httpx
from mcp.server.fastmcp import FastMCP

logging.basicConfig(
    level=getattr(logging, os.environ.get("LOG_LEVEL", "INFO").upper(), logging.INFO),
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
logger = logging.getLogger(__name__)


class ExecutionBackend(str, Enum):
    API = "api"
    BROWSER = "browser"
    HYBRID = "hybrid"


@dataclass(frozen=True)
class RuntimeSettings:
    target_url: str
    port: int
    request_timeout_seconds: float
    browser_timeout_ms: int
    api_max_retries: int
    browser_max_retries: int
    retry_backoff_seconds: float
    allow_unsafe_automation: bool
    browser_headless: bool
    session_ttl_seconds: int
    max_sessions: int
    log_level: str

    @classmethod
    def from_env(cls) -> "RuntimeSettings":
        return cls(
            target_url=os.environ.get("TARGET_URL", "{graph.source_url or 'https://example.com'}"),
            port=int(os.environ.get("PORT", "8000")),
            request_timeout_seconds=float(os.environ.get("REQUEST_TIMEOUT_SECONDS", "30")),
            browser_timeout_ms=int(os.environ.get("BROWSER_TIMEOUT_MS", "30000")),
            api_max_retries=int(os.environ.get("API_MAX_RETRIES", "2")),
            browser_max_retries=int(os.environ.get("BROWSER_MAX_RETRIES", "1")),
            retry_backoff_seconds=float(os.environ.get("RETRY_BACKOFF_SECONDS", "0.5")),
            allow_unsafe_automation=os.environ.get("AGENT_SEE_ALLOW_UNSAFE_AUTOMATION", "false").lower() == "true",
            browser_headless=os.environ.get("BROWSER_HEADLESS", "true").lower() != "false",
            session_ttl_seconds=int(os.environ.get("SESSION_TTL_SECONDS", "3600")),
            max_sessions=int(os.environ.get("MAX_SESSIONS", "200")),
            log_level=os.environ.get("LOG_LEVEL", "INFO").upper(),
        )


SETTINGS = RuntimeSettings.from_env()
logging.getLogger().setLevel(getattr(logging, SETTINGS.log_level, logging.INFO))

mcp = FastMCP(
    "{graph.source_url or 'converted-saas'}",
    description="Agent-optimized interface for {graph.source_url or 'SaaS application'}",
)

ROUTE_MAP = {route_map_json}
APPROVAL_POLICY = {approval_map_json}
TOOL_METADATA = {tool_metadata_json}
FORM_MAPPINGS = {form_mappings_json}
SCRAPING_RULES = {scraping_rules_json}
RUNTIME_STATE = {runtime_state_json}

AUTH_HEADERS: dict[str, str] = {{}}
if os.environ.get("API_KEY"):
    AUTH_HEADERS["Authorization"] = f"Bearer {{os.environ['API_KEY']}}"
if os.environ.get("API_KEY_HEADER") and os.environ.get("API_KEY_VALUE"):
    AUTH_HEADERS[os.environ["API_KEY_HEADER"]] = os.environ["API_KEY_VALUE"]

STATUS_ERROR_MAP = {{
    400: "INVALID_PARAM",
    401: "AUTH_FAILED",
    402: "PAYMENT_REQUIRED",
    403: "AUTH_FAILED",
    404: "NOT_FOUND",
    408: "UNAVAILABLE",
    409: "CONFLICT",
    429: "RATE_LIMITED",
    500: "SERVER_ERROR",
    502: "UNAVAILABLE",
    503: "UNAVAILABLE",
    504: "UNAVAILABLE",
}}
RETRYABLE_STATUS_CODES = {{408, 425, 429, 500, 502, 503, 504}}
REQUIRED_RUNTIME_ENV = ["TARGET_URL"]
SESSIONS: dict[str, dict[str, Any]] = {{}}


def _utc_now() -> datetime:
    return datetime.now(UTC)


def _isoformat(dt: datetime) -> str:
    return dt.isoformat().replace("+00:00", "Z")


def _prune_sessions() -> None:
    if not SESSIONS:
        return
    now = _utc_now()
    expired_ids: list[str] = []
    for session_id, session in SESSIONS.items():
        expires_at = session.get("expires_at")
        if isinstance(expires_at, str):
            expiry = datetime.fromisoformat(expires_at.replace("Z", "+00:00"))
            if expiry <= now:
                expired_ids.append(session_id)
    for session_id in expired_ids:
        SESSIONS.pop(session_id, None)


def _ensure_session(tool_name: str) -> tuple[str | None, dict[str, Any] | None]:
    metadata = TOOL_METADATA.get(tool_name, {{}})
    if not metadata.get("requires_session"):
        return None, None

    _prune_sessions()
    if len(SESSIONS) >= SETTINGS.max_sessions:
        raise RuntimeError(
            f"Session capacity exceeded: {{len(SESSIONS)}} active sessions, max {{SETTINGS.max_sessions}}"
        )

    created_at = _utc_now()
    expires_at = created_at.timestamp() + SETTINGS.session_ttl_seconds
    session_id = f"sess_{{uuid.uuid4().hex[:12]}}"
    session = {{
        "session_id": session_id,
        "tool_name": tool_name,
        "created_at": _isoformat(created_at),
        "expires_at": _isoformat(datetime.fromtimestamp(expires_at, tz=UTC)),
        "workflow_states": RUNTIME_STATE.get("workflow_states", {{}}),
        "entities": RUNTIME_STATE.get("session_entities", []),
    }}
    SESSIONS[session_id] = session
    return session_id, session


def _runtime_requirements() -> dict[str, bool]:
    return {{
        key: bool(os.environ.get(key))
        for key in REQUIRED_RUNTIME_ENV
    }}


def _readiness_summary() -> dict[str, int]:
    counts: dict[str, int] = {{}}
    for metadata in TOOL_METADATA.values():
        readiness = str(metadata.get("readiness", "unknown"))
        counts[readiness] = counts.get(readiness, 0) + 1
    return counts


def _operational_snapshot() -> dict[str, Any]:
    _prune_sessions()
    return {{
        "service": "{graph.source_url or 'converted-saas'}",
        "tool_count": len(TOOL_METADATA),
        "route_count": len(ROUTE_MAP.get("routes", {{}})),
        "readiness_summary": _readiness_summary(),
        "active_sessions": len(SESSIONS),
        "approval_bypass_enabled": SETTINGS.allow_unsafe_automation,
        "browser_headless": SETTINGS.browser_headless,
        "required_env": _runtime_requirements(),
    }}


def _health_payload() -> dict[str, Any]:
    return {{
        "status": "ok",
        "timestamp": _isoformat(_utc_now()),
        "snapshot": _operational_snapshot(),
    }}


def _readiness_payload() -> dict[str, Any]:
    required_env = _runtime_requirements()
    missing = [key for key, present in required_env.items() if not present]
    browser_runtime_available = True
    try:
        import playwright.async_api  # noqa: F401
    except Exception:
        browser_runtime_available = False

    return {{
        "status": "ready" if not missing else "degraded",
        "missing_required_env": missing,
        "browser_runtime_available": browser_runtime_available,
        "snapshot": _operational_snapshot(),
    }}


@mcp.tool()
async def healthcheck() -> dict:
    """Return a lightweight health snapshot for the generated runtime."""
    return _health_payload()


@mcp.tool()
async def readiness() -> dict:
    """Return runtime readiness information and configuration posture."""
    return _readiness_payload()


@mcp.tool()
async def runtime_snapshot() -> dict:
    """Return operational metadata for debugging and deployment inspection."""
    return {{
        "settings": asdict(SETTINGS),
        "tool_metadata": TOOL_METADATA,
        "runtime_state": RUNTIME_STATE,
        "snapshot": _operational_snapshot(),
    }}


def _check_approval(tool_name: str, params: dict[str, Any]) -> dict[str, Any] | None:
    policy = APPROVAL_POLICY.get(tool_name, {{}})
    if not policy.get("require_confirmation"):
        return None
    if SETTINGS.allow_unsafe_automation:
        return None

    return {{
        "error": "PAYMENT_REQUIRED",
        "message": "Human confirmation is required before executing this tool.",
        "tool": tool_name,
        "approval_required": True,
        "policy_notes": policy.get("notes", []),
        "recovery": "Set AGENT_SEE_ALLOW_UNSAFE_AUTOMATION=true only in explicitly approved, controlled environments.",
        "params_preview": params,
    }}


async def _sleep_before_retry(attempt: int, tool_name: str, reason: str) -> None:
    delay = SETTINGS.retry_backoff_seconds * (2 ** max(0, attempt - 1))
    logger.warning(
        "Retrying tool %s after attempt %s due to transient failure: %s",
        tool_name,
        attempt,
        reason,
    )
    if delay > 0:
        await asyncio.sleep(delay)


def _error_envelope(
    tool_name: str,
    error: str,
    message: str,
    *,
    status: int | None = None,
    attempts: int | None = None,
) -> dict[str, Any]:
    envelope: dict[str, Any] = {{
        "error": error,
        "message": message,
        "operational_status": TOOL_METADATA.get(tool_name, {{}}),
    }}
    if status is not None:
        envelope["status"] = status
    if attempts is not None:
        envelope["attempts"] = attempts
    return envelope


async def execute_tool(
    tool_name: str,
    params: dict[str, Any],
    backend: ExecutionBackend,
) -> dict[str, Any]:
    """Execute a tool against the original site with bounded operational behavior."""
    approval_result = _check_approval(tool_name, params)
    if approval_result is not None:
        return approval_result

    try:
        session_id, session = _ensure_session(tool_name)
    except RuntimeError as exc:
        return _error_envelope(tool_name, "UNAVAILABLE", str(exc))

    if backend == ExecutionBackend.API:
        result = await _execute_via_api(tool_name, params)
    elif backend == ExecutionBackend.BROWSER:
        result = await _execute_via_browser(tool_name, params)
    else:
        result = await _execute_via_hybrid(tool_name, params)

    metadata = TOOL_METADATA.get(tool_name, {{}})
    result.setdefault("_tool", tool_name)
    result.setdefault("_readiness", metadata.get("readiness", "structural_only"))
    result.setdefault("_verification", metadata.get("verification", "structural"))
    if session_id:
        result.setdefault("session_id", session_id)
        result.setdefault("session", session)
    return result


async def _execute_via_hybrid(tool_name: str, params: dict[str, Any]) -> dict[str, Any]:
    api_result = await _execute_via_api(tool_name, params)
    if "error" not in api_result:
        return api_result
    logger.warning(
        "Hybrid execution falling back to browser for %s after API failure: %s",
        tool_name,
        api_result.get("message", api_result.get("error", "unknown error")),
    )
    browser_result = await _execute_via_browser(tool_name, params)
    browser_result.setdefault("_fallback_from", "api")
    return browser_result


async def _execute_via_api(tool_name: str, params: dict[str, Any]) -> dict[str, Any]:
    routes = ROUTE_MAP.get("routes", {{}})
    route = routes.get(tool_name)
    if not route:
        return _error_envelope(tool_name, "NOT_FOUND", f"No API route for {{tool_name}}")

    base_url = ROUTE_MAP.get("base_url", SETTINGS.target_url)
    method = route["method"]
    path = route["path"]

    for param_name in route.get("path_params", []):
        value = params.get(param_name, "")
        path = path.replace({runtime_path_placeholder_expr}, str(value))

    url = f"{{base_url}}{{path}}"
    query = {{key: params[key] for key in route.get("query_params", []) if key in params}}
    body_params = route.get("body_params", [])
    body = (
        {{key: params[key] for key in body_params if key in params}}
        if body_params
        else None
    )

    headers = {{
        "Accept": "application/json",
        "User-Agent": "AgentSee/0.1 (MCP Executor)",
        **AUTH_HEADERS,
    }}
    if body is not None:
        headers["Content-Type"] = route.get("content_type", "application/json")

    for attempt in range(1, SETTINGS.api_max_retries + 2):
        try:
            async with httpx.AsyncClient(timeout=SETTINGS.request_timeout_seconds) as client:
                response = await client.request(
                    method=method,
                    url=url,
                    params=query or None,
                    json=body,
                    headers=headers,
                )
        except httpx.TimeoutException as exc:
            if attempt <= SETTINGS.api_max_retries:
                await _sleep_before_retry(attempt, tool_name, str(exc))
                continue
            return _error_envelope(
                tool_name,
                "UNAVAILABLE",
                f"Request timed out after {{attempt}} attempt(s)",
                attempts=attempt,
            )
        except httpx.TransportError as exc:
            if attempt <= SETTINGS.api_max_retries:
                await _sleep_before_retry(attempt, tool_name, str(exc))
                continue
            return _error_envelope(
                tool_name,
                "UNAVAILABLE",
                f"Transport failure after {{attempt}} attempt(s): {{exc}}",
                attempts=attempt,
            )

        if response.status_code in RETRYABLE_STATUS_CODES and attempt <= SETTINGS.api_max_retries:
            await _sleep_before_retry(attempt, tool_name, f"HTTP {{response.status_code}}")
            continue

        if response.status_code >= 400:
            message = f"HTTP {{response.status_code}}"
            try:
                error_body = response.json()
                if isinstance(error_body, dict):
                    message = error_body.get("message", error_body.get("error", message))
            except Exception:
                message = response.text[:200] if response.text else message
            return _error_envelope(
                tool_name,
                STATUS_ERROR_MAP.get(response.status_code, "SERVER_ERROR"),
                str(message),
                status=response.status_code,
                attempts=attempt,
            )

        content_type = response.headers.get("content-type", "")
        if "json" in content_type:
            data = response.json()
            if isinstance(data, list):
                return {{"items": data, "count": len(data), "_attempts": attempt, "_transport": "api"}}
            if isinstance(data, dict):
                data.setdefault("_attempts", attempt)
                data.setdefault("_transport", "api")
                return data
            return {{"result": data, "_attempts": attempt, "_transport": "api"}}

        return {{
            "status": "success",
            "status_code": response.status_code,
            "body": response.text[:2000],
            "_attempts": attempt,
            "_transport": "api",
        }}

    return _error_envelope(tool_name, "SERVER_ERROR", "Unhandled API execution state")


async def _execute_via_browser(tool_name: str, params: dict[str, Any]) -> dict[str, Any]:
    try:
        from agent_see.execution.browser_executor import (
            BrowserExecutionError,
            BrowserExecutor,
            FormMapping,
            ScrapingRule,
        )
    except ImportError:
        return _error_envelope(
            tool_name,
            "UNAVAILABLE",
            "Browser runtime dependencies are not available",
        )

    form_mappings = [FormMapping(**item) for item in FORM_MAPPINGS]
    scraping_rules = [ScrapingRule(**item) for item in SCRAPING_RULES]
    executor = BrowserExecutor(
        base_url=SETTINGS.target_url,
        form_mappings=form_mappings,
        scraping_rules=scraping_rules,
        headless=SETTINGS.browser_headless,
        timeout_ms=SETTINGS.browser_timeout_ms,
        max_retries=SETTINGS.browser_max_retries,
        retry_backoff_seconds=SETTINGS.retry_backoff_seconds,
    )

    try:
        result = await executor.execute(tool_name, params)
        result.setdefault("operational_status", TOOL_METADATA.get(tool_name, {{}}))
        return result
    except BrowserExecutionError as exc:
        return _error_envelope(tool_name, exc.code, exc.message)
    except Exception as exc:
        return _error_envelope(tool_name, "SERVER_ERROR", str(exc))


# === Generated Tools ===
{tools_code}


def main() -> None:
    logger.info(
        "Starting MCP runtime on port %s for %s",
        SETTINGS.port,
        SETTINGS.target_url,
    )
    mcp.run()


if __name__ == "__main__":
    main()
'''


def _python_type(json_type: str) -> str:
    """Convert JSON Schema type to Python type hint."""
    type_map = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
    }
    return type_map.get(json_type, "str")


def _distribution_name(graph: CapabilityGraph) -> str:
    """Generate a PEP 503-safe distribution name for the emitted runtime."""
    raw_name = (graph.source_url or "generated-mcp-server").split("//")[-1].split("/")[0]
    normalized = re.sub(r"[^a-z0-9]+", "-", raw_name.lower()).strip("-")
    return f"{normalized}-agent" if normalized else "generated-mcp-server"



def _generate_pyproject(graph: CapabilityGraph) -> str:
    """Generate pyproject.toml for the MCP server."""
    name = _distribution_name(graph)
    return f'''[project]
name = "{name}"
version = "0.1.0"
description = "Agent-optimized MCP server for {graph.source_url or 'SaaS application'}"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.0.0",
    "httpx>=0.27.0",
    "playwright>=1.40.0",
    "agent-see>=0.1.0",
]

[project.scripts]
{name.replace('-', '_')}_runtime = "server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-include = ["server.py"]
'''


def _generate_dockerfile() -> str:
    """Generate a more production-oriented Dockerfile for the emitted runtime."""
    return '''FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY . .

RUN pip install uv && uv pip install --system -e .
RUN playwright install chromium --with-deps

EXPOSE 8000
CMD ["python", "server.py"]
'''


def generate_mcp_server(
    graph: CapabilityGraph,
    tool_schemas: list[ToolSchema],
    output_dir: Path,
) -> None:
    """Generate a complete MCP server package with operational metadata."""
    output_dir.mkdir(parents=True, exist_ok=True)

    route_map = build_route_map(graph)
    server_code = _generate_server_py(graph, tool_schemas, route_map)
    (output_dir / "server.py").write_text(server_code)
    (output_dir / "route_map.json").write_text(json.dumps(route_map.to_dict(), indent=2))
    (output_dir / "tool_metadata.json").write_text(
        json.dumps(
            {
                schema.name: {
                    "backend": schema.execution_backend.value,
                    "readiness": schema.execution_readiness.value,
                    "verification": schema.verification_status.value,
                    "requires_session": schema.requires_session,
                    "approval_requirement": schema.approval_requirement.value,
                    "operational_notes": schema.operational_notes,
                }
                for schema in tool_schemas
            },
            indent=2,
        )
    )
    (output_dir / "runtime_state.json").write_text(
        json.dumps(graph.state_model.model_dump(), indent=2)
    )
    (output_dir / "operationalization_report.json").write_text(
        json.dumps(
            {
                "source": graph.source_url,
                "tool_count": len(tool_schemas),
                "readiness_summary": {
                    readiness: sum(
                        1
                        for schema in tool_schemas
                        if schema.execution_readiness.value == readiness
                    )
                    for readiness in sorted(
                        {schema.execution_readiness.value for schema in tool_schemas}
                    )
                },
                "tools": {
                    schema.name: {
                        "backend": schema.execution_backend.value,
                        "readiness": schema.execution_readiness.value,
                        "verification": schema.verification_status.value,
                        "requires_session": schema.requires_session,
                        "approval_requirement": schema.approval_requirement.value,
                        "operational_notes": schema.operational_notes,
                    }
                    for schema in tool_schemas
                },
            },
            indent=2,
        )
    )

    (output_dir / "pyproject.toml").write_text(_generate_pyproject(graph))
    (output_dir / "Dockerfile").write_text(_generate_dockerfile())

    from agent_see.execution.deployer import generate_deployment_configs

    app_name = (
        (graph.source_url or "converted-saas")
        .split("//")[-1]
        .split("/")[0]
        .replace(".", "-")
    )
    generate_deployment_configs(output_dir, app_name)

    tool_list = chr(10).join(
        f'- **{schema.name}**: {schema.description} '
        f'(backend: `{schema.execution_backend.value}`, readiness: `{schema.execution_readiness.value}`)'
        for schema in tool_schemas
    )
    readme = f"""# Agent Interface for {graph.source_url or 'SaaS Application'}

Auto-generated by Agent-See. This MCP runtime wraps the original site and
exposes {graph.capability_count} capabilities as structured tools.

## Operational posture

This package now includes a stronger operational baseline:

- bounded API retries for transient failures;
- bounded browser retries with explicit timeout controls;
- approval gates for sensitive operations;
- session TTL and session-capacity guardrails for stateful workflows;
- health, readiness, and runtime snapshot inspection tools.

It still does **not** claim that every generated tool is fully production-verified
against application drift. Use `tool_metadata.json`, `runtime_state.json`, and
`operationalization_report.json` to review readiness before deployment.

## Quick start

```bash
cp .env.example .env
# Edit .env with TARGET_URL, credentials, and runtime settings
uv run server.py
```

## Runtime inspection tools

The generated runtime includes these operator-facing tools in addition to the
converted business tools:

- `healthcheck`: lightweight health snapshot
- `readiness`: runtime readiness and dependency posture
- `runtime_snapshot`: configuration and metadata summary for debugging

## Tools

{tool_list}

## Runtime files

- `route_map.json`: grounded API route mapping used by API-backed tools
- `tool_metadata.json`: readiness, approval, and verification metadata per tool
- `runtime_state.json`: inferred session and workflow state scaffolding
- `operationalization_report.json`: machine-readable operational summary
"""
    (output_dir / "README.md").write_text(readme)

    logger.info("Generated MCP server with %s tools in %s", len(tool_schemas), output_dir)
