"""Generate a deployable MCP server package.

The generated server acts as a proxy: agents call structured tools,
the server translates them into API calls or browser automation
against the original site. This generator is intentionally explicit
about operational limits, approval gates, and stateful workflow scaffolding.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from agent_see.execution.browser_executor import (
    build_form_mappings_from_graph,
    build_scraping_rules_from_graph,
)
from agent_see.execution.route_map import RouteMap, build_route_map
from agent_see.models.capability import CapabilityGraph
from agent_see.models.schema import ToolSchema

logger = logging.getLogger(__name__)


def _generate_server_py(
    graph: CapabilityGraph,
    tool_schemas: list[ToolSchema],
    route_map: RouteMap,
) -> str:
    """Generate the main MCP server.py file with working execution scaffolding."""
    tool_registrations = []

    for schema in tool_schemas:
        func_name = schema.name
        params_str = ", ".join(
            f'{p.name}: {_python_type(p.type)}'
            + (f' = {repr(p.default)}' if not p.required else '')
            for p in schema.parameters
        )
        param_assignments = ("\n    ").join(
            f'params["{p.name}"] = {p.name}' for p in schema.parameters
        )

        if not params_str:
            params_str = ""
            param_assignments = "pass"

        tool_registrations.append(
            f'''
@mcp.tool()
async def {func_name}({params_str}) -> dict:
    """{schema.description}"""
    params = {{}}
    {param_assignments}
    return await execute_tool("{func_name}", params, ExecutionBackend.{schema.execution_backend.name})
'''
        )

    tools_code = "\n".join(tool_registrations)
    route_map_json = json.dumps(route_map.to_dict(), indent=2)
    approval_map_json = json.dumps(
        {
            schema.name: {
                "require_confirmation": schema.approval_requirement.value
                == "confirmation_required",
                "notes": schema.operational_notes,
            }
            for schema in tool_schemas
        },
        indent=2,
    )
    tool_metadata_json = json.dumps(
        {
            schema.name: {
                "backend": schema.execution_backend.value,
                "readiness": schema.execution_readiness.value,
                "verification": schema.verification_status.value,
                "requires_session": schema.requires_session,
                "approval_requirement": schema.approval_requirement.value,
            }
            for schema in tool_schemas
        },
        indent=2,
    )
    form_mappings_json = json.dumps(
        [mapping.__dict__ for mapping in build_form_mappings_from_graph(graph)], indent=2
    )
    scraping_rules_json = json.dumps(
        [rule.__dict__ for rule in build_scraping_rules_from_graph(graph)], indent=2
    )
    runtime_state_json = json.dumps(
        {
            "states": graph.state_model.states,
            "workflow_states": graph.state_model.workflow_states,
            "session_entities": graph.state_model.session_entities,
            "operational_notes": graph.state_model.operational_notes,
        },
        indent=2,
    )

    return f'''"""Auto-generated MCP server for {graph.source_url or 'SaaS application'}.

Generated by Agent-See v0.1.0
Capabilities: {graph.capability_count}
Source: {graph.source_url or 'N/A'}

Important: this server distinguishes interface generation from runtime readiness.
Approval-gated tools may require explicit human confirmation before execution.
"""

from __future__ import annotations

import logging
import os
import uuid
from datetime import datetime
from enum import Enum

import httpx
from mcp.server.fastmcp import FastMCP

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ExecutionBackend(str, Enum):
    API = "api"
    BROWSER = "browser"
    HYBRID = "hybrid"


mcp = FastMCP(
    "{graph.source_url or 'converted-saas'}",
    description="Agent-optimized interface for {graph.source_url or 'SaaS application'}",
)

TARGET_URL = os.environ.get("TARGET_URL", "{graph.source_url or 'https://example.com'}")
APPROVAL_BYPASS = os.environ.get("AGENT_SEE_ALLOW_UNSAFE_AUTOMATION", "false").lower() == "true"

ROUTE_MAP = {route_map_json}
APPROVAL_POLICY = {approval_map_json}
TOOL_METADATA = {tool_metadata_json}
FORM_MAPPINGS = {form_mappings_json}
SCRAPING_RULES = {scraping_rules_json}
RUNTIME_STATE = {runtime_state_json}

AUTH_HEADERS = {{}}
if os.environ.get("API_KEY"):
    AUTH_HEADERS["Authorization"] = f"Bearer {{os.environ['API_KEY']}}"
if os.environ.get("API_KEY_HEADER") and os.environ.get("API_KEY_VALUE"):
    AUTH_HEADERS[os.environ["API_KEY_HEADER"]] = os.environ["API_KEY_VALUE"]

STATUS_ERROR_MAP = {{
    400: "INVALID_PARAM",
    401: "AUTH_FAILED",
    403: "AUTH_FAILED",
    404: "NOT_FOUND",
    409: "CONFLICT",
    429: "RATE_LIMITED",
    402: "PAYMENT_REQUIRED",
    503: "UNAVAILABLE",
}}

SESSIONS: dict[str, dict] = {{}}


def _ensure_session(tool_name: str) -> tuple[str | None, dict | None]:
    metadata = TOOL_METADATA.get(tool_name, {{}})
    if not metadata.get("requires_session"):
        return None, None

    session_id = f"sess_{{uuid.uuid4().hex[:12]}}"
    session = {{
        "session_id": session_id,
        "tool_name": tool_name,
        "created_at": datetime.utcnow().isoformat() + "Z",
        "workflow_states": RUNTIME_STATE.get("workflow_states", {{}}),
        "entities": RUNTIME_STATE.get("session_entities", []),
    }}
    SESSIONS[session_id] = session
    return session_id, session


def _check_approval(tool_name: str, params: dict) -> dict | None:
    policy = APPROVAL_POLICY.get(tool_name, {{}})
    if not policy.get("require_confirmation"):
        return None
    if APPROVAL_BYPASS:
        return None

    return {{
        "error": "PAYMENT_REQUIRED",
        "message": "Human confirmation is required before executing this tool.",
        "tool": tool_name,
        "approval_required": True,
        "policy_notes": policy.get("notes", []),
        "recovery": "Set AGENT_SEE_ALLOW_UNSAFE_AUTOMATION=true only in explicitly approved, controlled environments.",
        "params_preview": params,
    }}


async def execute_tool(
    tool_name: str,
    params: dict,
    backend: ExecutionBackend,
) -> dict:
    """Execute a tool against the original site.

    Routes to API executor or browser executor based on backend type and enforces
    approval gating for sensitive operations.
    """
    approval_result = _check_approval(tool_name, params)
    if approval_result is not None:
        return approval_result

    session_id, session = _ensure_session(tool_name)

    if backend == ExecutionBackend.API:
        result = await _execute_via_api(tool_name, params)
    elif backend == ExecutionBackend.BROWSER:
        result = await _execute_via_browser(tool_name, params)
    else:
        try:
            result = await _execute_via_api(tool_name, params)
        except Exception:
            result = await _execute_via_browser(tool_name, params)

    metadata = TOOL_METADATA.get(tool_name, {{}})
    result.setdefault("_tool", tool_name)
    result.setdefault("_readiness", metadata.get("readiness", "structural_only"))
    result.setdefault("_verification", metadata.get("verification", "structural"))
    if session_id:
        result.setdefault("session_id", session_id)
        result.setdefault("session", session)
    return result


async def _execute_via_api(tool_name: str, params: dict) -> dict:
    """Execute a tool via direct API call to the original site."""
    routes = ROUTE_MAP.get("routes", {{}})
    route = routes.get(tool_name)

    if not route:
        return {{
            "error": "NOT_FOUND",
            "message": f"No API route for {{tool_name}}",
            "operational_status": TOOL_METADATA.get(tool_name, {{}}),
        }}

    base_url = ROUTE_MAP.get("base_url", TARGET_URL)
    method = route["method"]
    path = route["path"]

    for param_name in route.get("path_params", []):
        value = params.get(param_name, "")
        path = path.replace("{" + param_name + "}", str(value))

    url = f"{{base_url}}{{path}}"
    query = {{k: params[k] for k in route.get("query_params", []) if k in params}}

    body = None
    body_params = route.get("body_params", [])
    if body_params:
        body = {{k: params[k] for k in body_params if k in params}}

    headers = {{
        "Accept": "application/json",
        "User-Agent": "AgentSee/0.1 (MCP Executor)",
        **AUTH_HEADERS,
    }}
    if body is not None:
        headers["Content-Type"] = route.get("content_type", "application/json")

    logger.info(f"Executing {{method}} {{url}}")

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.request(
            method=method,
            url=url,
            params=query or None,
            json=body,
            headers=headers,
        )

    if response.status_code >= 400:
        error_code = STATUS_ERROR_MAP.get(response.status_code, "SERVER_ERROR")
        message = f"HTTP {{response.status_code}}"
        try:
            error_body = response.json()
            if isinstance(error_body, dict):
                message = error_body.get("message", error_body.get("error", message))
        except Exception:
            message = response.text[:200] if response.text else message
        return {{
            "error": error_code,
            "message": str(message),
            "status": response.status_code,
            "operational_status": TOOL_METADATA.get(tool_name, {{}}),
        }}

    content_type = response.headers.get("content-type", "")
    if "json" in content_type:
        data = response.json()
        if isinstance(data, list):
            return {{"items": data, "count": len(data)}}
        if isinstance(data, dict):
            return data
        return {{"result": data}}

    return {{
        "status": "success",
        "status_code": response.status_code,
        "body": response.text[:2000],
    }}


async def _execute_via_browser(tool_name: str, params: dict) -> dict:
    """Execute a tool via Playwright browser automation scaffolding."""
    try:
        from agent_see.execution.browser_executor import (
            BrowserExecutionError,
            BrowserExecutor,
            FormMapping,
            ScrapingRule,
        )
    except ImportError:
        return {{"error": "UNAVAILABLE", "message": "Browser runtime dependencies are not available"}}

    form_mappings = [FormMapping(**item) for item in FORM_MAPPINGS]
    scraping_rules = [ScrapingRule(**item) for item in SCRAPING_RULES]
    executor = BrowserExecutor(
        base_url=TARGET_URL,
        form_mappings=form_mappings,
        scraping_rules=scraping_rules,
        headless=True,
    )

    try:
        result = await executor.execute(tool_name, params)
        result.setdefault("operational_status", TOOL_METADATA.get(tool_name, {{}}))
        return result
    except BrowserExecutionError as exc:
        return {{
            "error": exc.code,
            "message": exc.message,
            "operational_status": TOOL_METADATA.get(tool_name, {{}}),
        }}
    except Exception as exc:
        return {{
            "error": "SERVER_ERROR",
            "message": str(exc),
            "operational_status": TOOL_METADATA.get(tool_name, {{}}),
        }}


# === Generated Tools ===
{tools_code}

if __name__ == "__main__":
    mcp.run()
'''


def _python_type(json_type: str) -> str:
    """Convert JSON Schema type to Python type hint."""
    type_map = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
    }
    return type_map.get(json_type, "str")


def _generate_pyproject(graph: CapabilityGraph) -> str:
    """Generate pyproject.toml for the MCP server."""
    name = (
        (graph.source_url or "converted-saas")
        .split("//")[-1]
        .split("/")[0]
        .replace(".", "-")
    )
    return f'''[project]
name = "{name}-agent"
version = "0.1.0"
description = "Agent-optimized MCP server for {graph.source_url or 'SaaS application'}"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.0.0",
    "httpx>=0.27.0",
    "playwright>=1.40.0",
    "agent-see>=0.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.backends"
'''


def _generate_dockerfile() -> str:
    """Generate Dockerfile for one-command deployment."""
    return '''FROM python:3.12-slim

WORKDIR /app
COPY . .

RUN pip install uv && uv pip install --system -e .
RUN playwright install chromium --with-deps

EXPOSE 8000
CMD ["python", "server.py"]
'''


def generate_mcp_server(
    graph: CapabilityGraph,
    tool_schemas: list[ToolSchema],
    output_dir: Path,
) -> None:
    """Generate a complete, deployable MCP server package."""
    output_dir.mkdir(parents=True, exist_ok=True)

    route_map = build_route_map(graph)

    server_code = _generate_server_py(graph, tool_schemas, route_map)
    (output_dir / "server.py").write_text(server_code)
    (output_dir / "route_map.json").write_text(json.dumps(route_map.to_dict(), indent=2))
    (output_dir / "tool_metadata.json").write_text(
        json.dumps(
            {
                schema.name: {
                    "backend": schema.execution_backend.value,
                    "readiness": schema.execution_readiness.value,
                    "verification": schema.verification_status.value,
                    "requires_session": schema.requires_session,
                    "approval_requirement": schema.approval_requirement.value,
                    "operational_notes": schema.operational_notes,
                }
                for schema in tool_schemas
            },
            indent=2,
        )
    )
    (output_dir / "runtime_state.json").write_text(
        json.dumps(graph.state_model.model_dump(), indent=2)
    )

    pyproject = _generate_pyproject(graph)
    (output_dir / "pyproject.toml").write_text(pyproject)

    dockerfile = _generate_dockerfile()
    (output_dir / "Dockerfile").write_text(dockerfile)

    from agent_see.execution.deployer import generate_deployment_configs

    app_name = (
        (graph.source_url or "converted-saas")
        .split("//")[-1]
        .split("/")[0]
        .replace(".", "-")
    )
    generate_deployment_configs(output_dir, app_name)

    tool_list = chr(10).join(
        f'- **{s.name}**: {s.description} '
        f'(backend: `{s.execution_backend.value}`, readiness: `{s.execution_readiness.value}`)'
        for s in tool_schemas
    )
    readme = f"""# Agent Interface for {graph.source_url or 'SaaS Application'}

Auto-generated by Agent-See. This MCP server wraps the original site
and exposes {graph.capability_count} capabilities as structured tools.

## Operational Posture

This package separates **interface generation** from **operational hardening**.
It ships with:

- grounded route mappings where available
- generated browser scaffolding for UI-discovered actions
- explicit approval gates for sensitive operations
- starter-grade runtime state files for session-aware workflows

It does **not** claim that every tool is already live-verified against production drift.
Use `tool_metadata.json`, `runtime_state.json`, and `route_map.json` during hardening.

## Quick Start

```bash
cp .env.example .env
# Edit .env with TARGET_URL and API credentials
uv run server.py
```

## One-Click Deploy

```bash
# Fly.io
flyctl deploy

# Railway
railway up

# Docker Compose
docker compose up --build -d

# Or use the helper script
./deploy.sh
```

## Tools

{tool_list}

## Runtime Files

- `route_map.json`: grounded API route mapping used by API-backed tools
- `tool_metadata.json`: readiness, approval, and verification metadata per tool
- `runtime_state.json`: inferred session and workflow state scaffolding
"""
    (output_dir / "README.md").write_text(readme)

    logger.info(
        f"Generated MCP server with {len(tool_schemas)} tools in {output_dir}"
    )
