"""Generate a deployable MCP server that wraps the original SaaS.

The generated server acts as a proxy: agents call structured tools,
the server translates them into API calls or browser automation
against the original site.
"""

from __future__ import annotations

import logging
from pathlib import Path

from agent_see.models.capability import CapabilityGraph
from agent_see.models.schema import ExecutionBackend, ToolSchema

logger = logging.getLogger(__name__)


def _generate_server_py(
    graph: CapabilityGraph,
    tool_schemas: list[ToolSchema],
) -> str:
    """Generate the main MCP server.py file."""
    tool_imports = []
    tool_registrations = []

    for schema in tool_schemas:
        func_name = schema.name
        tool_imports.append(f"# Tool: {func_name}")

        params_str = ", ".join(
            f'{p.name}: {_python_type(p.type)}' + (f' = {repr(p.default)}' if not p.required else '')
            for p in schema.parameters
        )

        # Build JSON schema for parameters
        json_schema = schema.to_json_schema()

        tool_registrations.append(f'''
@mcp.tool()
async def {func_name}({params_str}) -> dict:
    """{schema.description}"""
    params = {{}}
    {chr(10).join(f'    params["{p.name}"] = {p.name}' for p in schema.parameters)}
    return await execute_tool("{func_name}", params, ExecutionBackend.{schema.execution_backend.name})
''')

    tools_code = "\n".join(tool_registrations)

    return f'''"""Auto-generated MCP server for {graph.source_url or 'SaaS application'}.

Generated by Agent-See v0.1.0
Capabilities: {graph.capability_count}
Source: {graph.source_url or 'N/A'}
"""

import json
import logging
from enum import Enum

from mcp.server.fastmcp import FastMCP

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ExecutionBackend(str, Enum):
    API = "api"
    BROWSER = "browser"
    HYBRID = "hybrid"


# Initialize MCP server
mcp = FastMCP(
    "{graph.source_url or 'converted-saas'}",
    description="Agent-optimized interface for {graph.source_url or 'SaaS application'}",
)

TARGET_URL = "{graph.source_url or 'https://example.com'}"


async def execute_tool(
    tool_name: str,
    params: dict,
    backend: ExecutionBackend,
) -> dict:
    """Execute a tool against the original site.

    Routes to API executor or browser executor based on the backend type.
    """
    if backend == ExecutionBackend.API:
        return await _execute_via_api(tool_name, params)
    elif backend == ExecutionBackend.BROWSER:
        return await _execute_via_browser(tool_name, params)
    else:
        # Hybrid: try API first, fall back to browser
        try:
            return await _execute_via_api(tool_name, params)
        except Exception:
            return await _execute_via_browser(tool_name, params)


async def _execute_via_api(tool_name: str, params: dict) -> dict:
    """Execute a tool via direct API call to the original site."""
    import httpx
    # TODO: Implement API routing based on discovered endpoints
    async with httpx.AsyncClient(base_url=TARGET_URL) as client:
        response = await client.get(f"/api/{{tool_name}}", params=params)
        return response.json()


async def _execute_via_browser(tool_name: str, params: dict) -> dict:
    """Execute a tool via Playwright browser automation."""
    # TODO: Implement browser automation for each tool
    return {{"status": "not_implemented", "tool": tool_name, "params": params}}


# === Generated Tools ===
{tools_code}

if __name__ == "__main__":
    mcp.run()
'''


def _python_type(json_type: str) -> str:
    """Convert JSON Schema type to Python type hint."""
    type_map = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
    }
    return type_map.get(json_type, "str")


def _generate_pyproject(graph: CapabilityGraph) -> str:
    """Generate pyproject.toml for the MCP server."""
    name = (graph.source_url or "converted-saas").split("//")[-1].split("/")[0].replace(".", "-")
    return f'''[project]
name = "{name}-agent"
version = "0.1.0"
description = "Agent-optimized MCP server for {graph.source_url or 'SaaS application'}"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.0.0",
    "httpx>=0.27.0",
    "playwright>=1.40.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.backends"
'''


def _generate_dockerfile() -> str:
    """Generate Dockerfile for one-command deployment."""
    return '''FROM python:3.12-slim

WORKDIR /app
COPY . .

RUN pip install uv && uv pip install --system -e .
RUN playwright install chromium --with-deps

EXPOSE 8000
CMD ["python", "server.py"]
'''


def generate_mcp_server(
    graph: CapabilityGraph,
    tool_schemas: list[ToolSchema],
    output_dir: Path,
) -> None:
    """Generate a complete, deployable MCP server package.

    Args:
        graph: The capability graph
        tool_schemas: Tool schemas for each capability
        output_dir: Directory to write the server package
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # server.py
    server_code = _generate_server_py(graph, tool_schemas)
    (output_dir / "server.py").write_text(server_code)

    # pyproject.toml
    pyproject = _generate_pyproject(graph)
    (output_dir / "pyproject.toml").write_text(pyproject)

    # Dockerfile
    dockerfile = _generate_dockerfile()
    (output_dir / "Dockerfile").write_text(dockerfile)

    # README
    readme = f"""# Agent Interface for {graph.source_url or 'SaaS Application'}

Auto-generated by Agent-See. This MCP server wraps the original site
and exposes {graph.capability_count} capabilities as structured tools.

## Run

```bash
uv run server.py
```

## Deploy

```bash
docker build -t agent-wrapper .
docker run -p 8000:8000 agent-wrapper
```

## Tools

{chr(10).join(f'- **{s.name}**: {s.description}' for s in tool_schemas)}
"""
    (output_dir / "README.md").write_text(readme)

    logger.info(
        f"Generated MCP server with {len(tool_schemas)} tools in {output_dir}"
    )
