"""Generate an OpenAPI 3.1 spec for the agent-optimized interface."""

from __future__ import annotations

from agent_see.models.capability import CapabilityGraph
from agent_see.models.schema import ToolSchema


def generate_openapi_spec(
    graph: CapabilityGraph,
    tool_schemas: list[ToolSchema],
) -> dict:
    """Generate an OpenAPI 3.1 specification.

    Every tool becomes an endpoint with operationId (critical for agent tool calling).
    """
    source = graph.source_url or "converted-saas"

    paths: dict = {}
    for schema in tool_schemas:
        path = f"/tools/{schema.name}"
        operation = {
            "operationId": schema.name,
            "summary": schema.description,
            "tags": [schema.domain],
            "requestBody": {
                "required": True,
                "content": {
                    "application/json": {
                        "schema": schema.to_json_schema(),
                    }
                },
            },
            "responses": {
                "200": {
                    "description": "Successful response",
                    "content": {
                        "application/json": {
                            "schema": schema.to_output_schema(),
                        }
                    },
                },
                "400": {"description": "Invalid parameters"},
                "404": {"description": "Resource not found"},
                "500": {"description": "Server error"},
            },
        }

        paths[path] = {"post": operation}

    return {
        "openapi": "3.1.0",
        "info": {
            "title": f"Agent Interface for {source}",
            "description": f"Agent-optimized API with {len(tool_schemas)} tools. "
            f"Generated by Agent-See.",
            "version": "0.1.0",
        },
        "paths": paths,
    }
